# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 3, 23, 20, 6, 21, 748284), verbose_name='Опубликована'),
        ),
    ]
