# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160325_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 3, 25, 19, 57, 39, 654563), verbose_name='Опубликована'),
        ),
    ]
