# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160325_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 3, 28, 21, 39, 20, 725130), verbose_name='Опубликована'),
        ),
    ]
