# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Пользователь')),
                ('posted', models.DateField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'запись гостевой книги',
                'ordering': ['-posted'],
                'verbose_name_plural': 'записи гостевой книги',
            },
        ),
    ]
