# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price_acc',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена с учетом скидки, руб.'),
        ),
    ]
